export const QUERYURL = 'QueryUrl'
export const APIHTTPS = 'Api-Https'
export const CHANGESTORE = 'CHANGESTORE'
export const ISLOADING = 'ISLOADING'
export const HEADTOP = 'head-top'
export const ERRORiMG = 'error-img'
